#!/bin/bash
# Deploy Unified GLMP Home Page
# Makes the database table the STAR of the GLMP experience
# Created: $(date)

set -e

echo "=========================================================="
echo "🚀 DEPLOYING UNIFIED GLMP HOME PAGE"
echo "=========================================================="
echo ""
echo "This deployment:"
echo "  ✅ Makes database table the primary content"
echo "  ✅ Features 100:12:7:2 pattern prominently"
echo "  ✅ Single page experience (no viewer confusion)"
echo "  ✅ Search and filter functionality"
echo "  ✅ Clean, modern design"
echo ""

BUCKET="gs://regal-scholar-453620-r7-podcast-storage"

# Deploy unified home page as the main index
echo "📤 Deploying unified-glmp-home.html as main index..."
gsutil -h "Cache-Control:no-cache, no-store, must-revalidate" \
       -h "Content-Type:text/html" \
       cp unified-glmp-home.html "$BUCKET/index.html"

echo ""
echo "✅ Deployment complete!"
echo ""
echo "=========================================================="
echo "🧪 VERIFICATION STEPS"
echo "=========================================================="
echo ""
echo "IMPORTANT: Test in Incognito mode!"
echo ""
echo "1. Visit main URL:"
echo "   https://storage.googleapis.com/regal-scholar-453620-r7-podcast-storage/index.html"
echo ""
echo "2. Check hero header:"
echo "   ✅ Should prominently display '100:12:7:2' pattern"
echo "   ✅ Clear explanation of what it means"
echo ""
echo "3. Check statistics dashboard:"
echo "   ✅ Shows 108 processes"
echo "   ✅ Shows ~7,150 nodes"
echo "   ✅ Shows OR, AND, NOT gate counts"
echo ""
echo "4. Check database table:"
echo "   ✅ All 108 processes visible"
echo "   ✅ Click process name → opens flowchart in new tab"
echo "   ✅ Sortable columns work"
echo ""
echo "5. Check search/filter:"
echo "   ✅ Search box filters processes"
echo "   ✅ Organism filter works"
echo "   ✅ Category filter works"
echo ""
echo "=========================================================="
echo "📊 WHAT'S NEW"
echo "=========================================================="
echo ""
echo "BEFORE:"
echo "  • Multiple pages (confusing navigation)"
echo "  • 'Viewer' terminology unclear"
echo "  • Database table hidden"
echo "  • Pattern not prominent"
echo ""
echo "AFTER:"
echo "  • Single unified page"
echo "  • Database table is the STAR 🌟"
echo "  • 100:12:7:2 pattern hero display"
echo "  • Search and filter built-in"
echo "  • Clean, focused messaging"
echo ""
echo "=========================================================="
echo "🎯 USER EXPERIENCE"
echo "=========================================================="
echo ""
echo "User Journey:"
echo "  1. Land on page → See 100:12:7:2 pattern immediately"
echo "  2. Statistics dashboard → Understand scale (108 processes)"
echo "  3. Pattern explanation → Learn what it means"
echo "  4. Search processes → Find what they need"
echo "  5. Click process → View interactive flowchart"
echo ""
echo "No confusion, no navigation, just pure database power!"
echo ""
echo "=========================================================="
echo "✅ UNIFIED GLMP HOME PAGE DEPLOYED!"
echo "=========================================================="
