#!/bin/bash
cd "$(dirname "$0")"
pandoc ADDENDUM_FOR_VEJDEMO_JOHANSSON.md -o ADDENDUM_FOR_VEJDEMO_JOHANSSON.pdf
pandoc ONE_PAGE_SUMMARY.md -o ONE_PAGE_SUMMARY.pdf
pandoc H1_LOOP_ANALYSIS.md -o H1_LOOP_ANALYSIS.pdf
pandoc BIOLOGICAL_COHERENCE_CHECK.md -o BIOLOGICAL_COHERENCE_CHECK.pdf
echo "Done."
